"use strict";
var data = require("./lib/data");
exports.data = data;
var methods = require("./lib/methods");
exports.methods = methods;
var surfaces = require("./lib/surfaces");
exports.surfaces = surfaces;
var MethodMaterial_1 = require("./lib/MethodMaterial");
exports.MethodMaterial = MethodMaterial_1.MethodMaterial;
var MethodMaterialMode_1 = require("./lib/MethodMaterialMode");
exports.MethodMaterialMode = MethodMaterialMode_1.MethodMaterialMode;
var SurfacePool_1 = require("@awayjs/renderer/lib/surfaces/SurfacePool");
SurfacePool_1.SurfacePool.registerAbstraction(surfaces.GL_MethodMaterialSurface, MethodMaterial_1.MethodMaterial);
